# Not in use for now
services:
  prom:
    build: 5.Metrics_Prometheus/
    ports:
      - 9090:9090
    expose:
<<<<<<< HEAD
      - 9090:9090
=======
      - 9090:9090
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
