apiVersion: v1
kind: Service
metadata:
  name: oncall
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: oncall
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - protocol: TCP
      name: metrics
      port: 9091
      targetPort: 9091
<<<<<<< HEAD:3.Oncall/oncall/service.yaml
      nodePort: 30001
=======
      nodePort: 30001
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b:3.OnCall/oncall/service.yaml
