apiVersion: v1
kind: Service
metadata:
  name: oncall
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: oncall
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - protocol: TCP
      name: metrics
      port: 9091
      targetPort: 9091
      nodePort: 30001
