apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics-account
<<<<<<< HEAD
    namespace: kube-state-metrics
=======
    namespace: kube-state-metrics
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
