apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics-account
      containers:
        - name: kube-state-metrics
          args:
            - '--resources=pods'
            - '--namespaces=kube-state-metrics,default'
<<<<<<< HEAD
          image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0
=======
          image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0                  
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
<<<<<<< HEAD
            periodSeconds: 20
=======
            periodSeconds: 20
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
