apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: kube-state-metrics
<<<<<<< HEAD
  type: ClusterIP
=======
  type: ClusterIP
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
