apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics-account
<<<<<<< HEAD
  namespace: kube-state-metrics
=======
  namespace: kube-state-metrics
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
