global:
  scrape_interval:     15s
scrape_configs:
  - job_name: 'prometheus'  
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'oncall'
    scrape_interval: 10s
    static_configs:
      - targets: ['oncall.metrics.local:8000']
  - job_name: 'kube-state'
    scrape_interval: 7s
    static_configs:
      - targets: ['localhost:8000']