---
- name: Set up webserver on Ubuntu
  hosts: all
  vars:
    user: Artem
  vars_files:
    - ./vars/site.yml
  tasks:
  # - name: Grant root privileges
  #   ansible.builtin.su:
        
    - name: Add nginx stable repository from PPA
      ansible.builtin.apt_repository:
        repo: 'ppa:nginx/stable'
        state: present
    - name: Ensure nginx is at the latest version
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: true
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: Create folder for data
      ansible.builtin.file:
        path: /data
        state: directory
        mode: u=rwx,g=rwx,o=rwx
    - name: Create subfolder for data
      ansible.builtin.file:
        path: /data/up1
        state: directory
        mode: u=rwx,g=rwx,o=rwx
    - name: Create index.html
      ansible.builtin.file:
        path: /data/up1/index.html
        state: touch
        mode: u=rwx,g=rwx,o=rwx
    - name: Create config file for nginx
      ansible.builtin.file:
        path: /etc/nginx/nginx.conf
        state: touch
        mode: u=rw,g=r,o=r    
    - name: Insert nginx configuration using template
      ansible.builtin.template:
        src: ./templates/nginx.j2
        dest: /etc/nginx/nginx.conf
    - name: Fill index.html with data using template
      ansible.builtin.template:
        src: ./templates/index.j2
        dest: /data/up1/index.html
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
