apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-prober
  labels:
    app: my-prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-prober
  template:
    metadata:
      labels:
        app: my-prober
    spec:
<<<<<<< HEAD
      serviceAccountName: prober-user-account
=======
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
      containers:
      - name: my-prober
        image: my-prober:latest
        env:
        - name: DOCKER_DB_BOOTSTRAP
          value: "1"
        imagePullPolicy: Never
        ports:
<<<<<<< HEAD
        - containerPort: 9092
=======
        - containerPort: 9092
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
