apiVersion: v1
kind: Service
metadata:
  name: my-prober
spec:
  type: NodePort
  selector:
    app: my-prober
  ports:
    - protocol: TCP
      name: app
      port: 9092
      targetPort: 9092
<<<<<<< HEAD
      nodePort: 30004
=======
      nodePort: 30004
>>>>>>> 8c4c1c3889567a10cfc12ed1e5b3b362a4b1337b
